// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  react_player_mp4: dynamic(() => import("./ReactPlayerMp4")),
  react_player_vimeo: dynamic(() => import("./ReactPlayerVimeo")),
  rich_text: dynamic(() => import("./RichText")),
};
